apiVersion: v1
kind: Pod
metadata:
  name: pod207
spec:
  containers:
  - image: hub.zahariev.pro/alpine
    name: main
    args:
    - /bin/sh
    - -c
    - sleep 86400
  nodeSelector:
    speed: fast