apiVersion: v1
kind: Pod
metadata:
  name: t305
  namespace: cherry
spec:
  containers:
  - image: hub.zahariev.pro/k8s-environ
    name: main
    env:
    - name: FRUIT
      value: "Did you know that cherries are red and tasty? :)"
    - name: FOCUSON
      value: "FRUIT"