---

apiVersion: v1
kind: Pod
metadata:
  name: observer-pod-x
spec:
  containers:
  - name: observer-container
    image: alpine
    command: ["sleep", "1d"]

---

apiVersion: v1
kind: Pod
metadata:
  name: observer-pod-y
spec:
  containers:
  - name: observer-container
    image: alpine
    command: ["sleep", "1d"]

---

apiVersion: v1
kind: Pod
metadata:
  name: observer-pod-z
spec:
  containers:
  - name: observer-container
    image: alpine
    command: ["sleep", "1d"]

---