apiVersion: batch/v1
kind: CronJob
metadata:
  name: five-job
spec: 
  schedule: "*/5 * * * *"
  jobTemplate:
    spec: 
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: alpine
            name: main
            args:
            - /bin/sh
            - -c
            - sleep 60
