apiVersion: v1
kind: Pod
metadata:
  annotations:
    purpose: homework
  labels:
    app: hw
  name: homework-2
  namespace: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-2