apiVersion: v1
kind: LimitRange
metadata:
  name: projectx-limits
spec:
  limits:
  - max:
      cpu: 500m
      memory: 500Mi
    min:
      cpu: 50m
      memory: 50Mi
    default:
      cpu: 100m
      memory: 100Mi
    type: Container
