apiVersion: v1
kind: ResourceQuota
metadata:
  name: projectx-quotas
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
    pods: 10
    services: 5
    count/deployments.apps: 2
    count/replicasets.apps: 2
