apiVersion: v1
kind: Namespace
metadata:
  name: cherry
---
apiVersion: v1
kind: Pod
metadata:
  name: t208
  namespace: cherry
  labels:
    app: cherry
spec:
  containers:
  - image: shekeriev/k8s-environ
    name: main
    env:
    - name: FRUIT
      value: "Did you know that cherries are red and tasty? :)"
    - name: FOCUSON
      value: "FRUIT"
---
apiVersion: v1
kind: Service
metadata:
  name: cherry-svc
  namespace: cherry
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32208
  selector:
    app: cherry
